# Generated by Django 2.2.4 on 2019-09-01 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tvdbID', models.CharField(max_length=25)),
                ('showName', models.CharField(max_length=50)),
                ('overview', models.CharField(max_length=100)),
                ('imdbID', models.CharField(max_length=25)),
                ('statusWatched', models.BooleanField(default=False)),
                ('runningStatus', models.CharField(max_length=50)),
                ('firstAired', models.DateField(blank=True, null=True)),
                ('siteRating', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=5, null=True)),
                ('userRating', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=5, null=True)),
                ('network', models.CharField(max_length=50)),
                ('genreList', models.TextField(blank=True, null=True)),
                ('lastUpdated', models.DateTimeField(blank=True, null=True)),
                ('banner', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('statusWatched', models.BooleanField(default=False)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tv_show.Show')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episodeName', models.CharField(blank=True, max_length=50, null=True)),
                ('episodeNumber', models.IntegerField()),
                ('firstAired', models.DateField(blank=True, null=True)),
                ('dateWatched', models.DateField(auto_now=True, null=True)),
                ('tvdbID', models.CharField(max_length=50)),
                ('overview', models.TextField(blank=True, null=True)),
                ('statusWatched', models.BooleanField(default=False)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tv_show.Season')),
            ],
        ),
    ]
