# Generated by Django 2.2.4 on 2019-08-27 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_id', models.CharField(max_length=25)),
                ('show_name', models.CharField(max_length=50)),
                ('overview', models.CharField(max_length=100)),
                ('imdb_id', models.CharField(max_length=25)),
                ('status_watched', models.BooleanField(default=False)),
                ('running_status', models.BooleanField(default=False)),
                ('first_air', models.DateField()),
                ('siteRating', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=5, null=True)),
                ('userRating', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=5, null=True)),
                ('network', models.CharField(max_length=50)),
                ('genre_list', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('Banner', models.CharField(max_length=100)),
                ('air_time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('status_watched', models.BooleanField(default=False)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tv_show.Show')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episodeName', models.CharField(blank=True, max_length=50, null=True)),
                ('number', models.IntegerField()),
                ('firstAired', models.DateField(blank=True, null=True)),
                ('date_watched', models.DateField(auto_now=True, null=True)),
                ('tvdbID', models.CharField(max_length=50)),
                ('overview', models.TextField(blank=True, null=True)),
                ('status_watched', models.BooleanField(default=False)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tv_show.Season')),
            ],
        ),
    ]
