# Generated by Django 2.2.4 on 2019-08-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tv_show', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='show_id',
            new_name='tvdbID',
        ),
        migrations.RemoveField(
            model_name='show',
            name='air_time',
        ),
        migrations.AddField(
            model_name='show',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
