# Generated by Django 2.2.4 on 2019-09-01 17:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tv_show', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='user',
        ),
        migrations.AddField(
            model_name='show',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
