# Generated by Django 2.2.4 on 2019-08-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tv_show', '0003_auto_20190831_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='first_air',
        ),
        migrations.AddField(
            model_name='show',
            name='firstAired',
            field=models.DateField(blank=True, null=True),
        ),
    ]
