# Generated by Django 2.2.4 on 2019-08-31 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tv_show', '0004_auto_20190831_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='runningStatus',
            new_name='running_status',
        ),
    ]
