# Generated by Django 2.2.4 on 2019-08-31 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tv_show', '0005_auto_20190831_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='date_watched',
            new_name='dateWatched',
        ),
        migrations.RenameField(
            model_name='episode',
            old_name='number',
            new_name='episodeNumber',
        ),
        migrations.RenameField(
            model_name='episode',
            old_name='status_watched',
            new_name='statusWatched',
        ),
        migrations.RenameField(
            model_name='season',
            old_name='status_watched',
            new_name='statusWatched',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Banner',
            new_name='banner',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='genre_list',
            new_name='genreList',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='imdb_id',
            new_name='imdbID',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='last_updated',
            new_name='lastUpdated',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='running_status',
            new_name='runningStatus',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='show_name',
            new_name='showName',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='status_watched',
            new_name='statusWatched',
        ),
    ]
